<div class="col-12">
    <div class="row">

        <table class="table">
            <thead>
                <tr>
                    <th scope="col">name</th>
                    <th scope="col">day</th>
                    <th scope="col">month</th>
                    <th scope="col">year</th>
                    <th scope="col">table_id</th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($list as $user): ?>
                <tr>
                    <td> <?php echo $user['name'] ?></td>
                    <td> <?php echo $user['day'] ?></td>
                    <td> <?php echo $user['month'] ?></td>
                    <td> <?php echo $user['year'] ?></td>
                    <td> <?php echo $user['table_id'] ?></td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>

<div class="col-12">
    <div class="row">
        <?php echo $this->tag->form("/admin/listLate"); ?>

        <div class="form-group">
            <label for="password">User ID</label>
            <?php echo $form->render('table_id'); ?>
        </div>

        <div class="form-group">
            <?php echo $form->render('submit'); ?>
        </div>

        <input type='hidden' name='<?= $this->security->getTokenKey() ?>' value='<?= $this->security->getToken() ?>'/>
        </form>
    </div>
</div>