<div class="col-12">
    <div class="row">
        <?php echo $this->tag->form("admin/setHour"); ?>

        <div class="form-group">
            <label for="email">введите время</label>
            <?php echo $form->render('time'); ?>
        </div>

        <div class="form-group">
            <?php echo $form->render('submit'); ?>
        </div>

        <input type='hidden' name='<?= $this->security->getTokenKey() ?>' value='<?= $this->security->getToken() ?>'/>
        </form>
    </div>
</div>