
<h1 class="text-center">admin page</h1>
<?php echo $this->tag->form("/admin/manageUsers"); ?>

<div class="form-group">
    <?php echo $form->render('yearTable'); ?>
</div>

<div class="form-group">
    <?php echo $form->render('monthTable'); ?>
</div>

<div class="form-group">
    <?php echo $form->render('submit'); ?>
</div>

<input type='hidden' name='<?= $this->security->getTokenKey() ?>' value='<?= $this->security->getToken() ?>'/>
</form>


<div class="col-12 ">
    <div class="row">

        <br>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th scope="col">день</th>
                    <?php foreach ($users as $user): ?>
                        <th scope="col"><?php echo $user->name; ?></th>
                    <?php endforeach; ?>
                </tr>
            </thead>

            <tbody id="mytab1">
            <?php foreach ($data as $currentDay=>$data): ?>
                <tr>
                    <td><?php echo $currentDay; ?> </td>

                    <?php foreach ($data as $userData): ?>
                        <td>


                            <div class="input-group mb-3">
                                <input type="text" class="form-control"  value="<?php echo round($userData['start_time'], 2) ?>" placeholder="<?php echo $userData['start_time'] ?>" aria-label="start_time" aria-describedby="button-addon2">
                                <div class="input-group-append">
                                    <button class="btn btn-outline-secondary"
                                            data-day="<?php echo $userData['day']?>"
                                            data-year="<?php echo $userData['year']?>"
                                            data-id="<?php echo $userData['id'] ?>"
                                            data-month="<?php echo $userData['month'] ?>"
                                            onclick="changeUsersTime(this);"
                                            type="button"
                                            id="button-addon2">
                                        Старт
                                    </button>
                                </div>
                            </div>

                            <div class="input-group mb-3">
                                <input type="text" class="form-control" placeholder="<?php echo round($userData['end_time'], 2) ?>" aria-label="end_time" aria-describedby="button-addon2">
                                <div class="input-group-append">
                                    <button class="btn btn-outline-secondary"
                                            data-day="<?php echo $userData['day']?>"
                                            data-year="<?php echo $userData['year']?>"
                                            data-id="<?php echo $userData['id'] ?>"
                                            data-month="<?php echo $userData['month'] ?>"
                                            onclick="changeUsersTimeStop(this);"
                                            type="button"
                                            id="button-addon2">
                                        Стоп
                                    </button>
                                </div>
                            </div>
                        </td>


                    <?php endforeach ?>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
