<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>Search user_late</h1>
    <p><?php echo $this->tag->linkTo(["user_late/new", "Create user_late"]) ?></p>
</div>

<?php echo $this->getContent() ?>

<form action="user_late/search" class="form-horizontal" method="get">
    <div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id", "size" => 30, "class" => "form-control", "id" => "fieldId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDay" class="col-sm-2 control-label">Day</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["day", "type" => "number", "class" => "form-control", "id" => "fieldDay"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldMonth" class="col-sm-2 control-label">Month</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["month", "type" => "number", "class" => "form-control", "id" => "fieldMonth"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldMonthName" class="col-sm-2 control-label">Month Of Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["month_name", "size" => 30, "class" => "form-control", "id" => "fieldMonthName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldYear" class="col-sm-2 control-label">Year</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["year", "type" => "number", "class" => "form-control", "id" => "fieldYear"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUserId" class="col-sm-2 control-label">User</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["user_id", "type" => "number", "class" => "form-control", "id" => "fieldUserId"]) ?>
    </div>
</div>


    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
        </div>
    </div>
</form>
