<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["user_late/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["user_late/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Day</th>
            <th>Month</th>
            <th>Month Of Name</th>
            <th>Year</th>
            <th>User</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $user_late): ?>
            <tr>
                <td><?php echo $user_late->getId() ?></td>
            <td><?php echo $user_late->getDay() ?></td>
            <td><?php echo $user_late->getMonth() ?></td>
            <td><?php echo $user_late->getMonthName() ?></td>
            <td><?php echo $user_late->getYear() ?></td>
            <td><?php echo $user_late->getUserId() ?></td>

                <td><?php echo $this->tag->linkTo(["user_late/edit/" . $user_late->getId(), "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["user_late/delete/" . $user_late->getId(), "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo(["user_late/search", "First", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["user_late/search?page=" . $page->before, "Previous", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["user_late/search?page=" . $page->next, "Next", 'class' => 'page-link']) ?></li>
                <li><?php echo $this->tag->linkTo(["user_late/search?page=" . $page->last, "Last", 'class' => 'page-link']) ?></li>
            </ul>
        </nav>
    </div>
</div>
